spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/fushuai?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
  devtools:
    restart:
      enabled: true  #设置开启热部署
      additional-paths: src/main/java/cn/kingcity/main #重启目录
      exclude: WEB-INF/**
server:
  port: 8081
mybatis-plus:
  #mapper-locations: classpath:/mapper/main/*Mapper.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
