spring:
  datasource:
    username: jason
    password: 21019581
#    username: root
#    password: 123456
    url: jdbc:mysql://localhost:3306/fushuai?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
  #设置开启热部署（已关闭）
  devtools:
    restart:
      enabled: false
      additional-paths: src/main/java/ #重启目录
      exclude: WEB-INF/** #排除热部署
server:
  port: 8081  #配置端口
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
